const SOURCES={virgilio:"https://sport.virgilio.it/calcio/serie-a/tabella-infortunati-squalificati-e-diffidati/",goal:"https://www.goal.com/it/notizie/tabella-infortunati-squalificati-e-diffidati-in-serie-a/1kw0ilrv37v1c10fvugourrggg"};
const TEAMS=["Atalanta","Bologna","Cagliari","Como","Cremonese","Fiorentina","Frosinone","Genoa","Inter","Juventus","Lazio","Lecce","Milan","Monza","Napoli","Parma","Pisa","Roma","Sassuolo","Torino","Udinese","Venezia","Verona"];
function decode(s){return String(s||"").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&agrave;/gi,"à").replace(/&egrave;/gi,"è").replace(/&igrave;/gi,"ì").replace(/&ograve;/gi,"ò").replace(/&ugrave;/gi,"ù").replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n)));}
function toText(h){return decode(String(h||"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<br\s*\/?>/gi,"\n").replace(/<\/(?:p|li|h1|h2|h3|h4|div|section|article|tr)>/gi,"\n").replace(/<[^>]+>/g," ")).replace(/\r/g,"").replace(/[ \t]+/g," ").replace(/\n[ \t]+/g,"\n").replace(/\n{2,}/g,"\n").trim();}
function norm(s){return String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9 ]/g," ").replace(/\s+/g," ").trim();}
function teamOf(l){const n=norm(l);return TEAMS.find(t=>norm(t)===n)||null;}
function dateOf(l){const m=String(l).match(/(?:Rientra\s+il|Rientro\s+il)\s+(\d{1,2})[-\/](\d{1,2})[-\/](\d{4})/i);return m?`${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`:null;}
function entry(l){const p=String(l).replace(/^[•*\-–—]\s*/,"").split(/\s+-\s+/).map(x=>x.trim()).filter(Boolean);return p.length<2?null:{name:p[0],reason:p.slice(1).join(" - ")};}
function parse(html,source){const lines=toText(html).split("\n").map(x=>x.trim()).filter(Boolean),out=[];let team=null,sec=null;for(const raw of lines){const line=raw.replace(/^[•*\-–—]\s*/,"").trim(),hit=teamOf(line.replace(/^#+\s*/,""));if(hit){team=hit;sec=null;continue}if(/^infortunati\b\s*:?\s*$/i.test(line)){sec="inj";continue}if(/^squalificati\b/i.test(line)){sec="sq";continue}if(/^diffidati\b/i.test(line)){sec="df";continue}if(sec!=="inj"||!team||/^(nessuno|nessun infortunato|[-–])$/i.test(line))continue;const e=entry(line);if(!e)continue;out.push({playerName:e.name,name:e.name,team,injured:true,status:"injured",type:"Injury",reason:e.reason,returnDate:dateOf(line),source})}return out}
function surname(n){const w=norm(n).split(" ").filter(Boolean);return w[w.length-1]||norm(n)}
function dedupe(rows){const m=new Map();for(const r of rows){const k=`${norm(r.team)}|${surname(r.name)}`,o=m.get(k);if(!o){m.set(k,{...r,sources:[r.source]});continue}const sources=[...new Set([...(o.sources||[o.source]),r.source])],goal=r.source==="Goal.com"?r:(o.source==="Goal.com"?o:null),c=goal||r;m.set(k,{...o,...c,returnDate:c.returnDate||o.returnDate||r.returnDate||null,sources,source:sources.join(" + ")})}return [...m.values()]}
async function get(url){const r=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0 (compatible; Fantascam/1.0)",Accept:"text/html,application/xhtml+xml"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.text()}
module.exports=async function handler(req,res){if(req.method!=="GET"){res.setHeader("Allow","GET");return res.status(405).json({error:"Method not allowed"})}res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Cache-Control","s-maxage=3600, stale-while-revalidate=14400");const x=await Promise.allSettled([get(SOURCES.virgilio),get(SOURCES.goal)]),d={Virgilio:{ok:false,count:0},Goal:{ok:false,count:0}};let rows=[];if(x[0].status==="fulfilled"){const a=parse(x[0].value,"Virgilio Sport");d.Virgilio={ok:true,count:a.length};rows.push(...a)}else d.Virgilio.error=String(x[0].reason?.message||x[0].reason);if(x[1].status==="fulfilled"){const a=parse(x[1].value,"Goal.com");d.Goal={ok:true,count:a.length};rows.push(...a)}else d.Goal.error=String(x[1].reason?.message||x[1].reason);const injuries=dedupe(rows);if(!injuries.length)return res.status(502).json({ok:false,error:"Nessuna fonte ha prodotto risultati",diagnostics:d,injuries:[],updatedAt:new Date().toISOString()});return res.status(200).json({ok:true,source:"Virgilio Sport + Goal.com",count:injuries.length,diagnostics:d,injuries,updatedAt:new Date().toISOString()})};